Repository boostcampwm-2022/Web10-MonumentGallery, pull requests merged in 2022-12, with the labels that each got.

#124 feat: 갤러리 페이지 히스토리 라우팅, 사진 플로트 애니메이션 구현(Resolve #116, Resolve #117)
  client/src/@types/colors.ts
  client/src/@types/gallery.ts
  client/src/GalleryPage/Gallery.tsx
  client/src/GalleryPage/GalleryPage.tsx
  client/src/GalleryPage/GalleryWorld.tsx
  client/src/GalleryPage/components/DomElements.tsx
  client/src/GalleryPage/components/SyncButton.tsx
  client/src/GalleryPage/components/ViewRotateController.tsx
  client/src/GalleryPage/mapObjects/Bridge.tsx
  client/src/GalleryPage/mapObjects/GalleryCenterIsland.tsx
  client/src/GalleryPage/mapObjects/GalleryPageIsland.tsx
  client/src/GalleryPage/mapObjects/MemorialStone.tsx
  client/src/GalleryPage/mapObjects/PictureFragments.tsx
  client/src/GalleryPage/mapObjects/pixelFragmentGeometry.ts
  client/src/GalleryPage/mapObjects/pixelFragmentShader.ts
  client/src/components/SpaceCreater/index.tsx
  client/src/components/ThemeSelector/index.tsx
  client/src/hooks/useGalleryHistorySave.ts
  client/src/store/gallery.store.ts
  server/router/galleryRouter.js
  server/service/sseService.js
Labels: frontend

#136 docs: readme 추가
  readme.md
Labels: documentation

#149 feat: 스크린샷 기능 구현
  client/src/GalleryPage/Gallery.tsx
  client/src/MainPage/MainCanvas.tsx
  client/src/components/Footer/index.tsx
  client/src/components/ScreenshotCapturer/index.tsx
Labels: frontend

#167 perf: 공간 렌더링 최적화 (resolve #163)
  client/src/@types/animator.ts
  client/src/@types/common.ts
  client/src/GalleryPage/ErrorPage.tsx
  client/src/GalleryPage/Gallery.tsx
  client/src/GalleryPage/components/CrossPointer/style.scss
  client/src/GalleryPage/mapObjects/AnimatedTitle.tsx
  client/src/GalleryPage/mapObjects/GalleryPageIsland.tsx
  client/src/GalleryPage/mapObjects/MemorialStone.tsx
  client/src/GalleryPage/mapObjects/SubWordCloud.tsx
  client/src/MainPage/mapObjects/Monument.tsx
  client/src/MainPage/mapObjects/Portal.tsx
  client/src/MainPage/mapObjects/TextRing.tsx
  client/src/MainPage/mapObjects/WordCloud.tsx
  client/src/components/Delayed/Delayed.tsx
  client/src/components/ProgressBar/style.scss
  client/src/hooks/useTriggeredSpring.ts
Labels: frontend

#175 refactor: 일부 의존성 제거
  client/create.html
  client/gallery.html
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/MainPage/MainWorld.tsx
  client/src/MainPage/components/SplashScreen/SplashScreen.tsx
  client/src/components/ProgressBar/index.tsx
  client/src/components/Spinner/index.tsx
  client/src/components/Spinner/style.module.scss
  client/src/components/buttons/SuspenseButton.tsx
  server/index.js
Labels: frontend

#183 feat: 메인 페이지에 표지판 추가 → 클릭 시 서비스 소개 모달
  client/src/GalleryPage/Gallery.tsx
  client/src/MainPage/MainWorld.tsx
  client/src/MainPage/mapObjects/Environments/RoadSign/RoadSignHtml.tsx
  client/src/MainPage/mapObjects/Environments/RoadSign/index.tsx
  client/src/MainPage/mapObjects/Environments/RoadSign/style.scss
  client/src/MainPage/mapObjects/Environments/index.tsx
  client/src/MainPage/mapObjects/Plane.tsx
  client/src/assets/images/close.png
  client/src/assets/models/road-sign.glb
  client/src/components/Devtools/index.tsx
  client/src/components/Header/style.scss
  client/src/components/ProgressBar/index.tsx
  client/src/hooks/useAudio.ts
Labels: frontend

#185 fix: 노션 데이터베이스 페이지의 하위 페이지를 처리할 때 자신의 url을 누락하는 버그 수정
  client/src/layouts/FloatLayout/style.scss
  server/service/getNotionContentService.js
Labels: bug, backend

#207 perf: 개인 공간 렌더링 최적화 (resolve #186, resolve #188)
  client/create.html
  client/gallery.html
  client/index.html
  client/public/favicon.ico/manifest.json
  client/src/GalleryPage/components/HistorySidebar/index.tsx
  client/src/GalleryPage/mapObjects/GalleryPageIsland.tsx
  client/src/GalleryPage/mapObjects/PictureFragments.tsx
  client/src/GalleryPage/mapObjects/pixelFragmentGeometry.ts
  client/src/MainPage/MainWorld.tsx
  client/src/MainPage/components/SplashScreen/SplashScreen.tsx
  client/src/MainPage/mapObjects/Environments/RoadSign/index.tsx
  client/src/MainPage/mapObjects/Ground.tsx
  client/src/MainPage/mapObjects/Player.tsx
  client/src/MainPage/mapObjects/Portal.tsx
  client/src/assets/images/expand.png
  client/src/assets/images/fullscreen.svg
  client/src/assets/images/github.svg
  client/src/assets/images/header-logo.svg
  client/src/assets/images/headerLogo.svg
  client/src/assets/images/pause.png
  client/src/assets/images/pause.svg
  client/src/assets/images/play.png
  client/src/assets/images/play.svg
  client/src/assets/images/screenshot.svg
  client/src/assets/images/splash-logo-1x.png
  client/src/assets/images/splash-logo-2x.png
  client/src/assets/images/viewfinder.png
  client/src/components/Delayed/Delayed.tsx
  client/src/components/Footer/AudioHandler.tsx
  client/src/components/Footer/ExpandButton.tsx
  client/src/components/Footer/index.tsx
  client/src/components/Header/index.tsx
  client/src/components/Header/style.scss
  client/src/components/ThemeSelector/index.tsx
  client/src/hooks/useKeyMovement.ts
  client/src/utils/randomPosition.json
  server/index.js
  server/service/galleryService.js
Labels: frontend

#222 refactor: 프론트엔드 코드 리팩토링
  client/src/@types/gallery.ts
  client/src/@types/main.ts
  client/src/CreatePage/CreatePage.tsx
  client/src/GalleryPage/Gallery.tsx
  client/src/GalleryPage/components/SyncButton/SyncSpaceCreater.tsx
  client/src/GalleryPage/mapObjects/AnimatedTitle.tsx
  client/src/GalleryPage/mapObjects/Balloon.tsx
  client/src/GalleryPage/mapObjects/Bridge.tsx
  client/src/GalleryPage/mapObjects/GalleryCenterIsland.tsx
  client/src/GalleryPage/mapObjects/GalleryPageIsland.tsx
  client/src/GalleryPage/mapObjects/MemorialStone.tsx
  client/src/GalleryPage/mapObjects/Monolith.tsx
  client/src/GalleryPage/mapObjects/Pedestal.tsx
  client/src/GalleryPage/mapObjects/Sign.tsx
  client/src/MainPage/MainCanvas.tsx
  client/src/MainPage/MainPage.tsx
  client/src/MainPage/MainWorld.tsx
  client/src/MainPage/components/MapDataFetcher.tsx
  client/src/MainPage/mapObjects/Ground.tsx
  client/src/MainPage/mapObjects/Monolith.tsx
  client/src/MainPage/mapObjects/Pedestal.tsx
  client/src/MainPage/mapObjects/Player.tsx
  client/src/components/SpaceCreater/index.tsx
  client/src/components/ThemeSelector/index.tsx
  client/src/constants/colors.ts
  client/src/constants/positions.ts
  client/src/constants/texture.ts
  client/src/constants/theme.ts
  client/src/hooks/useGalleryHistorySave.ts
  client/src/hooks/useKeyMovement.ts
  client/src/hooks/useObjGeometry.ts
  client/src/store/audio.store.ts
  client/src/store/gallery.store.ts
  client/src/store/theme.store.ts
  client/src/utils/random.ts
Labels: frontend

#233 modify: 도움말 모달 관련 기능 수정
  client/src/CreatePage/CreatePage.tsx
  client/src/GalleryPage/Gallery.tsx
  client/src/GalleryPage/components/DomElements.tsx
  client/src/GalleryPage/components/GalleryHelp.tsx
  client/src/GalleryPage/dummyData.ts
  client/src/GalleryPage/mapObjects/Easel.tsx
  client/src/GalleryPage/mapObjects/Environments/index.tsx
  client/src/GalleryPage/mapObjects/GalleryCenterIsland.tsx
  client/src/MainPage/MainPage.tsx
  client/src/MainPage/MainWorld.tsx
  client/src/MainPage/components/MainHelp.tsx
  client/src/MainPage/mapObjects/Environments/index.tsx
  client/src/MainPage/mapObjects/FloatSign.tsx
  client/src/MainPage/mapObjects/RoadSign.tsx
  client/src/assets/images/easel-texture.png
  client/src/assets/images/help.svg
  client/src/assets/models/easel.obj
  client/src/assets/models/road-sign.glb
  client/src/components/Footer/Helper.tsx
  client/src/components/Footer/ScreenshotButton.tsx
  client/src/components/Footer/helper.scss
  client/src/components/Footer/index.tsx
  client/src/components/Footer/style.scss
  client/src/components/RoadSign/RoadSignHtml.tsx
  client/src/components/RoadSign/index.tsx
  client/src/hooks/useZoom.ts
Labels: frontend

#236 hotfix: 제목이 없을 때 자연어 처리가 불가능한 버그 수정
  client/src/@types/gallery.ts
  client/src/GalleryPage/GalleryWorld.tsx
  client/src/store/gallery.store.ts
  server/service/dataProcessService.js
Labels: bug, frontend, backend
